# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ChapterLink.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChapterLinkDialog(object):
    def setupUi(self, ChapterLinkDialog):
        ChapterLinkDialog.setObjectName("ChapterLinkDialog")
        ChapterLinkDialog.resize(340, 180)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/assets/icons/bg-icon.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        ChapterLinkDialog.setWindowIcon(icon)
        ChapterLinkDialog.setStyleSheet(
            "border-radius: 6px;\n" "background-color: rgb(20, 20, 20);"
        )
        ChapterLinkDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ChapterLinkDialog)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(ChapterLinkDialog)
        font = QtGui.QFont()
        font.setFamily("DroidSansMono NF")
        self.label.setFont(font)
        self.label.setStyleSheet(
            "margin: 0 6px;\n" "color: #ECECEC;\n" "background-color: transparent;"
        )
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem2)
        self.linkInput = QtWidgets.QLineEdit(ChapterLinkDialog)
        font = QtGui.QFont()
        font.setFamily("Iosevka NF")
        self.linkInput.setFont(font)
        self.linkInput.setToolTip("")
        self.linkInput.setStyleSheet(
            "QLineEdit {\n"
            "    padding: 6px;\n"
            "    margin: 0 6px;\n"
            "    color: #ECECEC;\n"
            "    border: 0.5px solid #ECECEC;\n"
            "    border-radius: 4px;\n"
            "    background-color: transparent;\n"
            "}"
        )
        self.linkInput.setInputMask("")
        self.linkInput.setText("")
        self.linkInput.setObjectName("linkInput")
        self.verticalLayout.addWidget(self.linkInput)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem6)
        self.cancel_dialog_btn = QtWidgets.QPushButton(ChapterLinkDialog)
        font = QtGui.QFont()
        font.setFamily("DroidSansMono NF")
        self.cancel_dialog_btn.setFont(font)
        self.cancel_dialog_btn.setStyleSheet(
            "border-radius: 4px;\n"
            "padding: 6px 18px;\n"
            "background-color: rgb(244, 164, 173);\n"
            "color: rgb(20, 20, 20);"
        )
        self.cancel_dialog_btn.setObjectName("cancel_dialog_btn")
        self.horizontalLayout.addWidget(self.cancel_dialog_btn)
        spacerItem7 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem7)
        self.load_chapter_btn = QtWidgets.QPushButton(ChapterLinkDialog)
        font = QtGui.QFont()
        font.setFamily("DroidSansMono NF")
        self.load_chapter_btn.setFont(font)
        self.load_chapter_btn.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 4px;\n"
            "    padding: 6px 18px;\n"
            "    margin-right: 6px;\n"
            "    background-color: rgba(85, 255, 255, 190);\n"
            "    color: rgb(20, 20, 20);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(85, 255, 255);\n"
            "}"
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/assets/icons/load.jpeg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.load_chapter_btn.setIcon(icon1)
        self.load_chapter_btn.setObjectName("load_chapter_btn")
        self.horizontalLayout.addWidget(self.load_chapter_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ChapterLinkDialog)
        QtCore.QMetaObject.connectSlotsByName(ChapterLinkDialog)

    def retranslateUi(self, ChapterLinkDialog):
        _translate = QtCore.QCoreApplication.translate
        ChapterLinkDialog.setWindowTitle(
            _translate("ChapterLinkDialog", "Chapter Link")
        )
        self.label.setText(_translate("ChapterLinkDialog", "Enter Chapter Link:"))
        self.linkInput.setPlaceholderText(
            _translate(
                "ChapterLinkDialog",
                "Enter chapter link from one of the available sources...",
            )
        )
        self.cancel_dialog_btn.setToolTip(_translate("ChapterLinkDialog", "Cancel"))
        self.cancel_dialog_btn.setText(_translate("ChapterLinkDialog", "Cancel"))
        self.load_chapter_btn.setToolTip(
            _translate("ChapterLinkDialog", "Load Link Chapter")
        )
        self.load_chapter_btn.setStatusTip(
            _translate("ChapterLinkDialog", "Load Link Chapter")
        )
        self.load_chapter_btn.setText(_translate("ChapterLinkDialog", "Load"))


import tensura_rc
