# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/SlimeReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InitialScreen(object):
    def setupUi(self, InitialScreen):
        InitialScreen.setObjectName("InitialScreen")
        InitialScreen.resize(640, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InitialScreen.sizePolicy().hasHeightForWidth())
        InitialScreen.setSizePolicy(sizePolicy)
        InitialScreen.setMinimumSize(QtCore.QSize(640, 360))
        InitialScreen.setMaximumSize(QtCore.QSize(640, 360))
        InitialScreen.setBaseSize(QtCore.QSize(640, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/bg-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InitialScreen.setWindowIcon(icon)
        InitialScreen.setToolTip("")
        InitialScreen.setStyleSheet("border-radius: 6px;\n"
"background-color: rgb(20, 20, 20);")
        InitialScreen.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(InitialScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 360))
        self.centralwidget.setMaximumSize(QtCore.QSize(640, 360))
        self.centralwidget.setBaseSize(QtCore.QSize(640, 360))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(632, 352))
        self.frame.setMaximumSize(QtCore.QSize(632, 352))
        self.frame.setBaseSize(QtCore.QSize(632, 352))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame {\n"
"    background-image: url(:/images/assets/images/tensura.jpg);\n"
"    background-color: rgb(20, 20, 20);\n"
"    border-radius: 6px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 621, 161))
        font = QtGui.QFont()
        font.setFamily("mononoki NF")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(85, 255, 255);\n"
"    background-color: transparent;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.online = QtWidgets.QRadioButton(self.frame)
        self.online.setGeometry(QtCore.QRect(140, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("FiraMono NF")
        font.setPointSize(11)
        self.online.setFont(font)
        self.online.setStyleSheet("background-color: transparent;\n"
"color: rgb(85, 255, 255);")
        self.online.setObjectName("online")
        self.offline = QtWidgets.QRadioButton(self.frame)
        self.offline.setGeometry(QtCore.QRect(140, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("FiraMono NF")
        font.setPointSize(11)
        self.offline.setFont(font)
        self.offline.setStyleSheet("background-color: transparent;\n"
"color: rgb(85, 255, 255);")
        self.offline.setObjectName("offline")
        self.site_select = QtWidgets.QComboBox(self.frame)
        self.site_select.setGeometry(QtCore.QRect(350, 200, 181, 31))
        font = QtGui.QFont()
        font.setFamily("FiraMono NF")
        font.setPointSize(12)
        self.site_select.setFont(font)
        self.site_select.setStyleSheet("background-color: rgba(20, 20, 20, 120);\n"
"color: rgb(85, 255, 255);\n"
"border-radius: 6px;")
        self.site_select.setObjectName("site_select")
        self.site_select.addItem("")
        self.site_select.addItem("")
        self.ok_btn = QtWidgets.QPushButton(self.frame)
        self.ok_btn.setGeometry(QtCore.QRect(370, 270, 161, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrainsMonoMedium NF")
        font.setPointSize(11)
        self.ok_btn.setFont(font)
        self.ok_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 4px;\n"
"    background-color: rgba(85, 255, 255, 190);\n"
"    color: rgb(20, 20, 20);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 255, 255);\n"
"}")
        self.ok_btn.setIcon(icon)
        self.ok_btn.setObjectName("ok_btn")
        self.exit_btn = QtWidgets.QPushButton(self.frame)
        self.exit_btn.setGeometry(QtCore.QRect(150, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrainsMonoMedium NF")
        font.setPointSize(11)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 4px;\n"
"    background-color: rgba(244, 164, 173, 200);\n"
"    color: rgb(20, 20, 20);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(244, 164, 173);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/icons/exit.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon1)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout.addWidget(self.frame)
        InitialScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(InitialScreen)
        QtCore.QMetaObject.connectSlotsByName(InitialScreen)

    def retranslateUi(self, InitialScreen):
        _translate = QtCore.QCoreApplication.translate
        InitialScreen.setWindowTitle(_translate("InitialScreen", "Tensura Reader"))
        self.label.setText(_translate("InitialScreen", "TENSURA"))
        self.online.setToolTip(_translate("InitialScreen", "Read using Google online TTS"))
        self.online.setText(_translate("InitialScreen", "Online Reader"))
        self.offline.setToolTip(_translate("InitialScreen", "Read with offline tools(Requires some installations)"))
        self.offline.setText(_translate("InitialScreen", "Offline Reader"))
        self.site_select.setToolTip(_translate("InitialScreen", "Choose site to read from.."))
        self.site_select.setItemText(0, _translate("InitialScreen", "NovelsOnline.net"))
        self.site_select.setItemText(1, _translate("InitialScreen", "NovelFull.com"))
        self.ok_btn.setToolTip(_translate("InitialScreen", "Start reading your the light novel"))
        self.ok_btn.setText(_translate("InitialScreen", "Enter Tempest"))
        self.exit_btn.setToolTip(_translate("InitialScreen", "Exit application"))
        self.exit_btn.setText(_translate("InitialScreen", "Exit To Milim"))
import tensura_rc
